/**
 * Cooksmart
 * Recipe management platform, realised as a pre-project for our SWT EnPro
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Recipe } from './recipe';
import { SimplePageable } from './simple-pageable';


export interface SimplePageRecipe { 
    page: number;
    totalPages: number;
    first: boolean;
    last: boolean;
    size: number;
    totalElements: number;
    pageable: SimplePageable;
    content: Array<Recipe>;
}

